### ISSUE TITLE
Having this package loaded breaks code relying on magmas Order function

### ISSUE THREAD

**Issue by koffie** [AndrewVSutherland/Magma#9]
Hi,

I was recently debugging some code that works perfectly without this package loaded but silently produce wrong results when this package is loaded. The reason is that magma has the following builtin function

```
Order(a::RngIntElt, m::RngIntElt) -> RngIntElt

The least integer k with 0 < k < m such that a^k = 1 mod m, (0 if a & m not 
coprime) [m > 1].
```

And this function is overwritten with different a different function here:

https://github.com/AndrewVSutherland/Magma/blob/7127aedebc93e14725a009d781adf9150d34f27e/chars.m#L773-L776

Could this function be removed or renamed so that it doesn't break other code relying on the magma builtin version of `Order(a::RngIntElt, m::RngIntElt) -> RngIntElt`

**Comment by AndrewVSutherland** [comment]
This intrinsic (and the Order intrinsic that takes a character label) has been renamed CharacterOrder.
